// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Wms.Models;

#nullable disable

namespace Wms.Migrations
{
    [DbContext(typeof(AppDataContext))]
    partial class AppDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("Wms.Models.Armazem", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("capacidade")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("enderecoid")
                        .HasColumnType("INTEGER");

                    b.Property<string>("nomeArmazem")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.HasIndex("enderecoid");

                    b.ToTable("Armazem");
                });

            modelBuilder.Entity("Wms.Models.Endereco", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("bairro")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("cep")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("cidade")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("complemento")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("estado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("numero")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("rua")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Endereco");
                });

            modelBuilder.Entity("Wms.Models.Pessoa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("enderecoid")
                        .HasColumnType("INTEGER");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("telefone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("enderecoid");

                    b.ToTable("Pessoas");

                    b.HasDiscriminator().HasValue("Pessoa");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Wms.Models.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Categoria")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("fornecedorId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("lote")
                        .HasColumnType("INTEGER");

                    b.Property<string>("nomeProduto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("preco")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("fornecedorId");

                    b.ToTable("Produto");
                });

            modelBuilder.Entity("Wms.Models.Usuario", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("cargo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("login")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("senha")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("Wms.Models.Cliente", b =>
                {
                    b.HasBaseType("Wms.Models.Pessoa");

                    b.Property<string>("cpf")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("Cliente");
                });

            modelBuilder.Entity("Wms.Models.Fornecedor", b =>
                {
                    b.HasBaseType("Wms.Models.Pessoa");

                    b.Property<string>("cnpj")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("Fornecedor");
                });

            modelBuilder.Entity("Wms.Models.Armazem", b =>
                {
                    b.HasOne("Wms.Models.Endereco", "endereco")
                        .WithMany()
                        .HasForeignKey("enderecoid");

                    b.Navigation("endereco");
                });

            modelBuilder.Entity("Wms.Models.Pessoa", b =>
                {
                    b.HasOne("Wms.Models.Endereco", "endereco")
                        .WithMany()
                        .HasForeignKey("enderecoid");

                    b.Navigation("endereco");
                });

            modelBuilder.Entity("Wms.Models.Produto", b =>
                {
                    b.HasOne("Wms.Models.Fornecedor", "fornecedor")
                        .WithMany()
                        .HasForeignKey("fornecedorId");

                    b.Navigation("fornecedor");
                });
#pragma warning restore 612, 618
        }
    }
}
