### GET - Listar todos os armazéns
GET http://localhost:5209/api/GetArmazem
Content-Type: application/json

### POST - Cadastrar armazém de teste
POST http://localhost:5209/api/PostArmazem
Content-Type: application/json

{
  "nomeArmazem": "Armazém de Teste",
  "status": "Ativo",
  "posicoes": 10,
  "produtoPosicao": 5,
  "enderecoId": 2
}

### PUT - Alterar armazém
PUT http://localhost:5209/api/PutArmazem=1
Content-Type: application/json

{
  "nomeArmazem": "Armazém de Teste Alterado",
  "status": "Ativo",
  "posicoes": 20,
  "produtoPosicao": 100,
  "enderecoId": 1
}

### DELETE - Deletar armazém
DELETE http://localhost:5209/api/DeleteArmazem=1
Content-Type: application/json
