### GET - Listar todos os clientes
GET http://localhost:5209/api/GetCliente
Content-Type: application/json

### POST - Cadastrar cliente de teste
POST http://localhost:5209/api/PostCliente
Content-Type: application/json

{
  "nome": "Cliente de Teste",
  "email": "cliente.teste@email.com",
  "telefone": "(11) 99999-0001",
  "cpf": "111.111.111-11",
  "enderecoId": 2
}

### PUT - Alterar cliente
PUT http://localhost:5209/api/PutCliente=1
Content-Type: application/json

{
  "nome": "Cliente de Teste Alterado",
  "email": "cliente.teste.alterado@email.com",
  "telefone": "(11) 99999-0002",
  "cpf": "111.111.111-11",
  "enderecoId": 1
}

### DELETE - Deletar cliente
DELETE http://localhost:5209/api/DeleteCliente=1
Content-Type: application/json
