### Listar Todos
GET http://localhost:5209/api/GetCliente

### Buscar por ID
GET http://localhost:5209/api/GetClienteById=1

### Buscar por CPF
GET http://localhost:5209/api/GetClienteByCpf=123.456.789-00

### Criar Novo (precisa de endereçoId)
POST http://localhost:5209/api/PostCliente
Content-Type: application/json

{
  "nome": "João Silva Santos",
  "email": "joao.silva@email.com",
  "telefone": "(11) 98765-4321",
  "cpf": "123.456.789-00",
  "enderecoId": 1
}

### Atualizar
PUT http://localhost:5209/api/PutCliente=1
Content-Type: application/json

{
  "nome": "João Silva Santos Junior",
  "email": "joao.junior@email.com",
  "telefone": "(11) 98765-9999",
  "cpf": "123.456.789-00",
  "enderecoId": 1
}

### Deletar
DELETE http://localhost:5209/api/DeleteCliente=1
