###############################################################################
#                           ENDPOINTS - ENDEREÇO
###############################################################################

### Listar Todos
GET http://localhost:5209/api/GetEndereco

### Buscar por ID
GET http://localhost:5209/api/GetEnderecoById=1

### Criar Novo
POST http://localhost:5209/api/PostEndereco
Content-Type: application/json

{    
  "rua": "Av. Paulista",
  "numero": "1000",
  "complemento": "Conjunto 101",
  "bairro": "Bela Vista",
  "cidade": "São Paulo",
  "estado": "SP",
  "cep": "01310-100"
}

### Atualizar
PUT http://localhost:5209/api/PutEndereco=1
Content-Type: application/json

{    
  "rua": "Av. Paulista",
  "numero": "2000",
  "complemento": "Andar 10",
  "bairro": "Bela Vista",
  "cidade": "São Paulo",
  "estado": "SP",
  "cep": "01310-200"
}

### Deletar
DELETE http://localhost:5209/api/DeleteEndereco=1
