### Listar Todas as Entradas
GET http://localhost:5209/api/GetEntradaProduto

### Buscar Entradas por ID da Entrada
GET http://localhost:5209/api/GetEntradaProdutoById=1

### Registrar Entrada de Produto em Posição Vazia
POST http://localhost:5209/api/PostEntradaProduto
Content-Type: application/json

{
  "fornecedorId": 1,
  "produtoId": 1,
  "quantidadeRecebida": 10,
  "inventarioId": 1
}

### Adicionar Mais do MESMO Produto (funciona!)
POST http://localhost:5209/api/PostEntradaProduto
Content-Type: application/json

{
  "fornecedorId": 1,
  "produtoId": 1,
  "quantidadeRecebida": 30,
  "inventarioId": 1
}

### TESTE DE ERRO: Tentar Adicionar Produto Diferente (vai dar erro!)
POST http://localhost:5209/api/PostEntradaProduto
Content-Type: application/json

{
  "fornecedorId": 1,
  "produtoId": 2,
  "quantidadeRecebida": 20,
  "inventarioId": 1
}

### Registrar Entrada em Outra Posição
POST http://localhost:5209/api/PostEntradaProduto
Content-Type: application/json

{
  "fornecedorId": 1,
  "produtoId": 2,
  "quantidadeRecebida": 75,
  "inventarioId": 2
}

### Deletar Registro de Entrada
DELETE http://localhost:5209/api/DeleteEntradaProduto=1&1
