###############################################################################
#                         ENDPOINTS - FORNECEDOR
###############################################################################

### Listar Todos
GET http://localhost:5209/api/GetFornecedor

### Buscar por ID
GET http://localhost:5209/api/GetFornecedorById=1

### Buscar por CNPJ
GET http://localhost:5209/api/GetFornecedorByCnpj=12.345.678/0001-90

### Criar Novo (precisa de endereçoId)
POST http://localhost:5209/api/PostFornecedor
Content-Type: application/json

{
  "nome": "Tech Distribuidor Ltda",
  "email": "contato@techdist.com.br",
  "telefone": "(11) 3344-5566",
  "cnpj": "12.345.678/0001-90",
  "enderecoId": 2
}

### Atualizar
PUT http://localhost:5209/api/PutFornecedor=1
Content-Type: application/json

{
  "nome": "Tech Distribuidor Nacional Ltda",
  "email": "vendas@techdist.com.br",
  "telefone": "(11) 3344-7788",
  "cnpj": "12.345.678/0001-90",
  "enderecoId": 2
}

### Deletar
DELETE http://localhost:5209/api/DeleteFornecedor=1
