
### Listar TODO o Inventário (retorna com nome do produto)
GET http://localhost:5209/api/GetInventario

### Buscar Posição por ID
GET http://localhost:5209/api/GetInventarioById=1

### Listar Inventário de um Armazém Específico
GET http://localhost:5209/api/GetInventarioByArmazem=1

### Buscar Onde Está um Produto Específico
GET http://localhost:5209/api/GetInventarioByProduto=1

### Listar Apenas Posições Vazias de um Armazém
GET http://localhost:5209/api/GetPosicoesVazias=1

### Remover Produto da Posição 
PUT http://localhost:5209/api/RemoverProduto=1

### Deletar Posição 
DELETE http://localhost:5209/api/DeleteInventario=1
