### GET - Listar todos os produtos
GET http://localhost:5209/api/GetProduto
Content-Type: application/json

### POST - Cadastrar produto de teste
POST http://localhost:5209/api/PostProduto
Content-Type: application/json

{
  "nomeProduto": "Produto de Teste",
  "descricao": "Descrição do produto de teste",
  "lote": 100,
  "fornecedorId": 1,
  "preco": 99.90,
  "categoria": 15
}

### PUT - Alterar produto
PUT http://localhost:5209/api/PutProduto=1
Content-Type: application/json

{
  "nomeProduto": "Produto de Teste Alterado",
  "descricao": "Descrição alterada do produto de teste",
  "lote": 200,
  "fornecedorId": 1,
  "preco": 149.90,
  "categoria": 15
}

### DELETE - Deletar produto
DELETE http://localhost:5209/api/DeleteProduto=1
Content-Type: application/json
