###############################################################################
#                           ENDPOINTS - USUÁRIO
###############################################################################

### Listar Todos
GET http://localhost:5209/api/GetUsuario

### Buscar por ID
GET http://localhost:5209/api/GetUsuarioById=1

### Buscar por Login
GET http://localhost:5209/api/GetUsuarioByLogin=admin

### Criar Novo
POST http://localhost:5209/api/PostUsuario
Content-Type: application/json

{
  "nome": "Administrador do Sistema",
  "login": "admin",
  "senha": "admin123",
  "cargo": "Administrador"
}

### Atualizar
PUT http://localhost:5209/api/PutUsuario=1
Content-Type: application/json

{
  "nome": "Super Administrador",
  "login": "admin",
  "senha": "superadmin456",
  "cargo": "Super Administrador"
}

### Deletar
DELETE http://localhost:5209/api/DeleteUsuario=1
