### GET - Listar todos os usuários
GET http://localhost:5209/api/GetUsuario
Content-Type: application/json

### POST - Cadastrar usuário de teste
POST http://localhost:5209/api/PostUsuario
Content-Type: application/json

{
  "nome": "Usuario de Teste",
  "login": "usuario.teste",
  "senha": "senha123",
  "cargo": "Operador"
}

### PUT - Alterar usuário
PUT http://localhost:5209/api/PutUsuario=1
Content-Type: application/json

{
  "nome": "Usuario de Teste Alterado",
  "login": "usuario.teste",
  "senha": "senha456",
  "cargo": "Gerente"
}

### DELETE - Deletar usuário
DELETE http://localhost:5209/api/DeleteUsuario=1
Content-Type: application/json
